channels:
  - pytorch
  - conda-forge
  - defaults
  - open3d-admin
  - anaconda

dependencies:
  - cubes
  - cudatoolkit=11.3
  - einops
  - flask
  - imageio
  - imageio-ffmpeg
  - jupyter
  - kornia
  - pillow>=9.1.0
  - plyfile
  - psycopg2
  - pycollada
  - python=3.7
  - python-dotenv
  - pytorch
  - pytorch-lightning=1.5.2
  - pyglet
  - matplotlib
  - networkx
  - notebook 
  - opencv
  # - libopencv 
  # - py-opencv
  # - ffmpeg 
  - open3d
  - scikit-learn-intelex
  - torch-optimizer
  - torchvision
  - trimesh